### PR TITLE
Use FAKE and Paket for building artifacts

### PR DESCRIPTION
**Pull request by objectx**
This PR utilizes [FAKE](https://fake.build) and [Paket](https://fsprojects.github.io/Paket/) to create artifacts.

Note: Currently Creating `*.pkg` for OSX feature is not implemented in `build.fsx` 😿

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thank you very much!!

**Comment by tategakibunko** [comment]
According to FAQ [What files should I commit?](https://fsprojects.github.io/Paket/faq.html#What-files-should-I-commit), `paket.lock` must be commited, and `paket.exe` must be ignored, so I've updated `.gitignore` a little.

[EDIT]
Ahh, `paket.lock` is auto generated... so you added to `.gitignored` temporary, thank you!

**Comment by objectx** [comment]
Committed `.paket/paket.exe` is a renamed version of `paket.bootstrapper.exe`.
I'll use the [magic mode](https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode), but the FAQ section seems not to touch it :open_mouth:

**Comment by tategakibunko** [comment]
Oh... that is why `paket.exe` is only 70kb... I get it. 
Then I'll restore `paket.exe`(`paket.bootstrapper.exe`) in `.gitignore`, thank you!

**Pull request closed without merging**
